{ name:
   { id: 'name',
     name: 'Name',
     source: 'npms',
     path: 'collected.metadata.name',
     process: ident },
  scope:
   { id: 'scope',
     name: 'Scope',
     source: 'npms',
     path: 'collected.metadata.scope',
     process: ident },
  version:
   { id: 'version',
     name: 'Version',
     source: 'npms',
     path: 'collected.metadata.version',
     process: ident },
  description:
   { id: 'description',
     name: 'Description',
     source: 'npms',
     path: 'collected.metadata.description',
     process: ident },
  keywords:
   { id: 'keywords',
     name: 'Keywords',
     source: 'npms',
     path: 'collected.metadata.keywords',
     process: joinComma },
  date:
   { id: 'date',
     name: 'Date',
     source: 'npms',
     path: 'collected.metadata.date',
     process: none },
  author:
   { id: 'author',
     name: 'Author',
     source: 'npms',
     path: 'collected.metadata.author',
     process: author },
  publisher:
   { id: 'publisher',
     name: 'Publisher',
     source: 'npms',
     path: 'collected.metadata.publisher',
     process: publisher },
  maintainers:
   { id: 'maintainers',
     name: 'Maintainers',
     source: 'npms',
     path: 'collected.metadata.maintainers',
     process: count },
  repository:
   { id: 'repository',
     name: 'Repository',
     source: 'npms',
     path: 'collected.metadata.links.repository',
     process: ident },
  npm:
   { id: 'npm',
     name: 'Npm',
     source: 'npms',
     path: 'collected.metadata.links.npm',
     process: ident },
  homepage:
   { id: 'homepage',
     name: 'Homepage',
     source: 'npms',
     path: 'collected.github.homepage',
     process: ident },
  bugs:
   { id: 'bugs',
     name: 'Bugs',
     source: 'npms',
     path: 'collected.metadata.links.bugs',
     process: ident },
  license:
   { id: 'license',
     name: 'License',
     source: 'npms',
     path: 'collected.metadata.license',
     process: none },
  dependencies:
   { id: 'dependencies',
     name: 'Dependencies',
     source: 'npms',
     path: 'collected.metadata.dependencies',
     process: count },
  releases:
   { id: 'releases',
     name: 'Releases',
     source: 'npms',
     path: 'collected.metadata.releases',
     process: releases },
  readme:
   { id: 'readme',
     name: 'Readme',
     source: 'npms',
     path: 'collected.metadata.readme',
     process: none },
  downloads:
   { id: 'downloads',
     name: 'Downloads',
     source: 'npms',
     path: 'collected.npm.downloads',
     process: downloads },
  dependentsCount:
   { id: 'dependentsCount',
     name: 'Dependents count',
     source: 'npms',
     path: 'evaluation.popularity.dependentsCount',
     process: ident },
  starsCount:
   { id: 'starsCount',
     name: 'Stars count',
     source: 'npms',
     path: 'collected.github.starsCount',
     process: ident },
  forksCount:
   { id: 'forksCount',
     name: 'Forks count',
     source: 'npms',
     path: 'collected.github.forksCount',
     process: ident },
  subscribersCount:
   { id: 'subscribersCount',
     name: 'Subscribers count',
     source: 'npms',
     path: 'collected.github.subscribersCount',
     process: ident },
  count:
   { id: 'count',
     name: 'Count',
     source: 'npms',
     path: 'collected.github.issues.count',
     process: ident },
  openCount:
   { id: 'openCount',
     name: 'Open count',
     source: 'npms',
     path: 'collected.github.issues.openCount',
     process: ident },
  distribution:
   { id: 'distribution',
     name: 'Distribution',
     source: 'npms',
     path: 'collected.github.issues.distribution',
     process: none },
  isDisabled:
   { id: 'isDisabled',
     name: 'Is disabled',
     source: 'npms',
     path: 'collected.github.issues.isDisabled',
     process: ident },
  contributors:
   { id: 'contributors',
     name: 'Contributors',
     source: 'npms',
     path: 'collected.github.contributors',
     process: paretoContributors },
  commits:
   { id: 'commits',
     name: 'Commits',
     source: 'npms',
     path: 'collected.github.commits',
     process: commits },
  statuses:
   { id: 'statuses',
     name: 'Statuses',
     source: 'npms',
     path: 'collected.github.statuses',
     process: none },
  readmeSize:
   { id: 'readmeSize',
     name: 'Readme size',
     source: 'npms',
     path: 'collected.source.files.readmeSize',
     process: ident },
  testsSize:
   { id: 'testsSize',
     name: 'Tests size',
     source: 'npms',
     path: 'collected.source.files.testsSize',
     process: ident },
  hasNpmIgnore:
   { id: 'hasNpmIgnore',
     name: 'Has npm ignore',
     source: 'npms',
     path: 'collected.source.files.hasNpmIgnore',
     process: ident },
  hasChangelog:
   { id: 'hasChangelog',
     name: 'Has changelog',
     source: 'npms',
     path: 'collected.source.files.hasChangelog',
     process: ident },
  badges:
   { id: 'badges',
     name: 'Badges',
     source: 'npms',
     path: 'collected.source.badges',
     process: none },
  linters:
   { id: 'linters',
     name: 'Linters',
     source: 'npms',
     path: 'collected.source.linters',
     process: linters },
  carefulness:
   { id: 'carefulness',
     name: 'Carefulness',
     source: 'npms',
     path: 'evaluation.quality.carefulness',
     process: ident },
  tests:
   { id: 'tests',
     name: 'Tests',
     source: 'npms',
     path: 'evaluation.quality.tests',
     process: ident },
  health:
   { id: 'health',
     name: 'Health',
     source: 'npms',
     path: 'evaluation.quality.health',
     process: ident },
  branding:
   { id: 'branding',
     name: 'Branding',
     source: 'npms',
     path: 'evaluation.quality.branding',
     process: ident },
  communityInterest:
   { id: 'communityInterest',
     name: 'Community interest',
     source: 'npms',
     path: 'evaluation.popularity.communityInterest',
     process: ident },
  downloadsCount:
   { id: 'downloadsCount',
     name: 'Downloads count',
     source: 'npms',
     path: 'evaluation.popularity.downloadsCount',
     process: ident },
  downloadsAcceleration:
   { id: 'downloadsAcceleration',
     name: 'Downloads acceleration',
     source: 'npms',
     path: 'evaluation.popularity.downloadsAcceleration',
     process: ident },
  releasesFrequency:
   { id: 'releasesFrequency',
     name: 'Releases frequency',
     source: 'npms',
     path: 'evaluation.maintenance.releasesFrequency',
     process: ident },
  commitsFrequency:
   { id: 'commitsFrequency',
     name: 'Commits frequency',
     source: 'npms',
     path: 'evaluation.maintenance.commitsFrequency',
     process: ident },
  openIssues:
   { id: 'openIssues',
     name: 'Open issues',
     source: 'npms',
     path: 'evaluation.maintenance.openIssues',
     process: ident },
  issuesDistribution:
   { id: 'issuesDistribution',
     name: 'Issues distribution',
     source: 'npms',
     path: 'evaluation.maintenance.issuesDistribution',
     process: ident },
  final:
   { id: 'final',
     name: 'Final',
     source: 'npms',
     path: 'score.final',
     process: ident },
  quality:
   { id: 'quality',
     name: 'Quality',
     source: 'npms',
     path: 'score.detail.quality',
     process: ident },
  popularity:
   { id: 'popularity',
     name: 'Popularity',
     source: 'npms',
     path: 'score.detail.popularity',
     process: ident },
  maintenance:
   { id: 'maintenance',
     name: 'Maintenance',
     source: 'npms',
     path: 'score.detail.maintenance',
     process: ident } }