module.exports = {
  label: {
     label: 'Name',
     source: 'npms',
     path: 'collected.metadata.name',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  scope: {
     label: 'Scope',
     source: 'npms',
     path: 'collected.metadata.scope',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  downloadsChart: {
    label: 'Downloads last year',
    source: 'npm_downloads',
    path: '',
    rawFn: 'ident',
    displayFn: 'ident',
    component: 'LineChart',
  },
  version: {
     label: 'Version',
     source: 'npms',
     path: 'collected.metadata.version',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  description: {
     label: 'Description',
     source: 'npms',
     path: 'collected.metadata.description',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  keywords: {
     label: 'Keywords',
     source: 'npms',
     path: 'collected.metadata.keywords',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'joinComma',
     component: 'Display',
  },
  author: {
     label: 'Author',
     source: 'npms',
     path: 'collected.metadata.author',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'author',
     component: 'Display',
  },
  publisher: {
     label: 'Publisher',
     source: 'npms',
     path: 'collected.metadata.publisher',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'publisher',
     component: 'Display',
  },
  maintainers: {
     label: 'Maintainers',
     source: 'npms',
     path: 'collected.metadata.maintainers',
     rawFn: 'ident',
     extractFn: 'count',
     displayFn: 'ident',
     component: 'SimpleBar',
  },
  repository: {
     label: 'Repository',
     source: 'npms',
     path: 'collected.metadata.links.repository',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Link',
  },
  npm: {
     label: 'NPM',
     source: 'npms',
     path: 'collected.metadata.links.npm',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Link',
  },
  homepage: {
     label: 'Homepage',
     source: 'npms',
     path: 'collected.github.homepage',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Link',
  },
  bugs: {
     label: 'Bugs',
     source: 'npms',
     path: 'collected.metadata.links.bugs',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Link',
  },
  license: {
     label: 'License',
     source: 'npms',
     path: 'collected.metadata.license',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  dependencies: {
     label: 'Dependencies',
     source: 'npms',
     path: 'collected.metadata.dependencies',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'count',
     component: 'Display',
  },
  releases: {
     label: 'Releases',
     source: 'npms',
     path: 'collected.metadata.releases',
     rawFn: 'ident',
     extractFn: 'releases',
     displayFn: 'ident',
     component: 'SimpleBar',
  },
  readme: {
     label: 'Readme',
     source: 'npms',
     path: 'collected.metadata.readme',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'shorten20chars',
     component: 'Display',
  },
  downloads: {
     label: 'Downloads in one year',
     source: 'npms',
     path: 'collected.npm.downloads',
     rawFn: 'ident',
     extractFn: 'downloads',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  dependentsCount: {
     label: 'Dependents count',
     source: 'npms',
     path: 'evaluation.popularity.dependentsCount',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  starsCount: {
     label: 'Stars count',
     source: 'npms',
     path: 'collected.github.starsCount',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  forksCount: {
     label: 'Forks count',
     source: 'npms',
     path: 'collected.github.forksCount',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  subscribersCount: {
     label: 'Subscribers count',
     source: 'npms',
     path: 'collected.github.subscribersCount',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  count: {
     label: 'Issues',
     source: 'npms',
     path: 'collected.github.issues.count',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  openCount: {
     label: 'Open issues',
     source: 'npms',
     path: 'collected.github.issues.openCount',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'SimpleBar',
  },
  distribution: {
     label: 'Average open issue duration',
     source: 'npms',
     path: 'collected.github.issues.distribution',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'averageOpenIssueDuration',
     component: 'SimpleBar',
  },
  isDisabled: {
     label: 'Is disabled',
     source: 'npms',
     path: 'collected.github.issues.isDisabled',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'SimpleBar',
  },
  contributors: {
     label: 'Contributors',
     source: 'npms',
     path: 'collected.github.contributors',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'paretoContributors',
     component: 'SimpleBar',
  },
  commits: {
     label: 'Commits',
     source: 'npms',
     path: 'collected.github.commits',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'commits',
     component: 'SimpleBar',
  },
  readmeSize: {
     label: 'Readme size',
     source: 'npms',
     path: 'collected.source.files.readmeSize',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  testsSize: {
     label: 'Tests size',
     source: 'npms',
     path: 'collected.source.files.testsSize',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  hasNpmIgnore: {
     label: 'Has npm ignore',
     source: 'npms',
     path: 'collected.source.files.hasNpmIgnore',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  hasChangelog: {
     label: 'Has changelog',
     source: 'npms',
     path: 'collected.source.files.hasChangelog',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'Display',
  },
  linters: {
     label: 'Linters',
     source: 'npms',
     path: 'collected.source.linters',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'linters',
     component: 'Display',
  },
  carefulness: {
     label: 'Carefulness',
     source: 'npms',
     path: 'evaluation.quality.carefulness',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  tests: {
     label: 'Tests',
     source: 'npms',
     path: 'evaluation.quality.tests',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  health: {
     label: 'Health',
     source: 'npms',
     path: 'evaluation.quality.health',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  branding: {
     label: 'Branding',
     source: 'npms',
     path: 'evaluation.quality.branding',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  communityInterest: {
     label: 'Community interest',
     source: 'npms',
     path: 'evaluation.popularity.communityInterest',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'ident',
     component: 'SimpleBar',
  },
  downloadsCount: {
     label: 'Downloads count',
     source: 'npms',
     path: 'evaluation.popularity.downloadsCount',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  downloadsAcceleration: {
     label: 'Downloads acceleration',
     source: 'npms',
     path: 'evaluation.popularity.downloadsAcceleration',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'thousands',
     component: 'SimpleBar',
  },
  releasesFrequency: {
     label: 'Releases frequency',
     source: 'npms',
     path: 'evaluation.maintenance.releasesFrequency',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  commitsFrequency: {
     label: 'Commits frequency',
     source: 'npms',
     path: 'evaluation.maintenance.commitsFrequency',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  openIssues: {
     label: 'Open issues',
     source: 'npms',
     path: 'evaluation.maintenance.openIssues',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  issuesDistribution: {
     label: 'Issues distribution',
     source: 'npms',
     path: 'evaluation.maintenance.issuesDistribution',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  quality: {
     label: 'Quality',
     source: 'npms',
     path: 'score.detail.quality',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  popularity: {
     label: 'Popularity',
     source: 'npms',
     path: 'score.detail.popularity',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  maintenance: {
     label: 'Maintenance',
     source: 'npms',
     path: 'score.detail.maintenance',
     rawFn: 'ident',
     extractFn: 'ident',
     displayFn: 'percent',
     component: 'SimpleBar',
  },
  final: {
    label: 'Final',
    source: 'npms',
    path: 'score.final',
    rawFn: 'ident',
    extractFn: 'ident',
    displayFn: 'percent',
    component: 'SimpleBar',
  },
};